"use client";
// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };

import Image from "next/image";
import "./admin.css";

import logo from "@/app/Assets/admin/logo.png";
import Link from "next/link";
import Cookies from "js-cookie";
import { useEffect, useState } from "react";
import { FaUserTie } from "react-icons/fa";

export default function RootLayout({ children }) {
  const [Loading, setLoading] = useState(true);
  const accessToken = Cookies.get("accessToken");
  const [userInfo, setUserInfo] = useState("");

  useEffect(() => {
    if (accessToken) {
      const getCookiesData = Cookies.get("CookieYouserData");
      const cookiesInfo = JSON.parse(getCookiesData);
      setUserInfo(cookiesInfo);
    }
    setLoading(false);
  }, [accessToken]);

  return (
    <html lang="en">
      <body className="">
        {Loading && (
          <>
            <div className="absolute w-[100%] bg-white h-[140vh] z-[1000]">
              <div class="flex space-x-2 justify-center items-center bg-white h-screen  ">
                <span class="sr-only">Loading...</span>
                <div class="h-8 w-8 bg-[#563A9F] rounded-full animate-bounce [animation-delay:-0.3s]"></div>
                <div class="h-8 w-8 bg-[#563A9F] rounded-full animate-bounce [animation-delay:-0.15s]"></div>
                <div class="h-8 w-8 bg-[#563A9F] rounded-full animate-bounce"></div>
              </div>
            </div>
          </>
        )}
        {userInfo?.ruler === "student" ? (
          <>
            <div className="d">
              <div class="h-screen w-screen bg-[#ffffffd1] flex justify-center items-center gap-5">
                <div class="relative inline-flex  group">
                  <div class="absolute transitiona-all duration-1000 opacity-70 -inset-px bg-gradient-to-r from-[#44BCFF] via-[#FF44EC] to-[#FF675E] rounded-xl blur-lg group-hover:opacity-100 group-hover:-inset-1 group-hover:duration-200 animate-tilt"></div>
                  <a
                    href="#"
                    title="Get quote now"
                    class="relative inline-flex items-center justify-center px-8 py-4 text-lg font-bold text-white transition-all duration-200 bg-gray-900 font-pj rounded-xl focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-900"
                    role="button"
                  >
                    You are not admin
                  </a>
                </div>
                <div class="relative inline-flex  group">
                  <div class="absolute transitiona-all duration-1000 opacity-70 -inset-px bg-gradient-to-r from-[#44BCFF] via-[#FF44EC] to-[#FF675E] rounded-xl blur-lg group-hover:opacity-100 group-hover:-inset-1 group-hover:duration-200 animate-tilt"></div>
                  <a
                    href="#"
                    title="Get quote now"
                    class="relative inline-flex items-center justify-center px-8 py-4 text-lg font-bold text-white transition-all duration-200 bg-gray-900 font-pj rounded-xl focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-900"
                    role="button"
                  >
                    Go
                  </a>
                </div>
                <div class="relative inline-flex  group">
                  <div class="absolute transitiona-all duration-1000 opacity-70 -inset-px bg-gradient-to-r from-[#44BCFF] via-[#FF44EC] to-[#FF675E] rounded-xl blur-lg group-hover:opacity-100 group-hover:-inset-1 group-hover:duration-200 animate-tilt"></div>
                  <Link
                    href="/"
                    title="Get quote now"
                    class="relative inline-flex items-center justify-center px-8 py-4 text-lg font-bold text-white transition-all duration-200 bg-gray-900 font-pj rounded-xl focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-900"
                    role="button"
                  >
                    Back Home
                  </Link>
                </div>
              </div>
            </div>
          </>
        ) : (
          <>
            <div className="flex w-[100%] mx-auto">
              <div className="flex  h-[100vh]">
                {/* ----- left site nav---- */}
                <aside class="hidden sm:flex sm:flex-col">
                  <Link
                    href="/admin"
                    class="inline-flex items-center justify-center h-20 w-20 bg-purple-600 hover:bg-purple-500 focus:bg-purple-500"
                  >
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width={35}
                      hanging={35}
                      viewBox="0 0 640 512"
                    >
                      <path
                        fill="#f7f7f7"
                        d="M320.7 352c8.1-89.7 83.5-160 175.3-160c8.9 0 17.6 .7 26.1 1.9L309.5 7c-6-5-14-7-21-7s-15 1-22 8L10 231.5c-7 7-10 15-10 24c0 18 14 32.1 32 32.1h32v69.7c-.1 .9-.1 1.8-.1 2.8V472c0 22.1 17.9 40 40 40h16c1.2 0 2.4-.1 3.6-.2c1.5 .1 3 .2 4.5 .2H160h24c22.1 0 40-17.9 40-40V448 384c0-17.7 14.3-32 32-32h64l.7 0zM640 368a144 144 0 1 0 -288 0 144 144 0 1 0 288 0zm-76.7-43.3c6.2 6.2 6.2 16.4 0 22.6l-72 72c-6.2 6.2-16.4 6.2-22.6 0l-40-40c-6.2-6.2-6.2-16.4 0-22.6s16.4-6.2 22.6 0L480 385.4l60.7-60.7c6.2-6.2 16.4-6.2 22.6 0z"
                      />
                    </svg>
                  </Link>
                  <div class="flex-grow flex flex-col justify-between text-gray-500 bg-gray-800">
                    <nav class="flex flex-col mx-4 my-6 space-y-4">
                      <Link
                        href="/admin/panding_post"
                        class="flex flex-col items-center justify-center py-3 hover:text-gray-400 hover:bg-gray-700 focus:text-gray-400 focus:bg-gray-700 rounded-lg"
                      >
                        {/* <span class="sr-only">Post</span> */}
                        <svg
                          xmlns="http://www.w3.org/2000/svg"
                          viewBox="0 0 512 512"
                          width={20}
                          height={20}
                        >
                          <path
                            fill="#ffffff"
                            d="M32 32H480c17.7 0 32 14.3 32 32V96c0 17.7-14.3 32-32 32H32C14.3 128 0 113.7 0 96V64C0 46.3 14.3 32 32 32zm0 128H480V416c0 35.3-28.7 64-64 64H96c-35.3 0-64-28.7-64-64V160zm128 80c0 8.8 7.2 16 16 16H336c8.8 0 16-7.2 16-16s-7.2-16-16-16H176c-8.8 0-16 7.2-16 16z"
                          />
                        </svg>
                        posts
                      </Link>
                      <Link
                        href="/admin/userAdmin"
                        class="flex flex-col items-center justify-center py-3 hover:text-gray-400 hover:bg-gray-700 focus:text-gray-400 focus:bg-gray-700 rounded-lg"
                      >
                        {/* <span class="sr-only">Post</span> */}
                        <svg
                          xmlns="http://www.w3.org/2000/svg"
                          viewBox="0 0 448 512"
                          width={20}
                          height={20}
                        >
                          <path
                            fill="#ffffff"
                            d="M96 128a128 128 0 1 0 256 0A128 128 0 1 0 96 128zm94.5 200.2l18.6 31L175.8 483.1l-36-146.9c-2-8.1-9.8-13.4-17.9-11.3C51.9 342.4 0 405.8 0 481.3c0 17 13.8 30.7 30.7 30.7H162.5c0 0 0 0 .1 0H168 280h5.5c0 0 0 0 .1 0H417.3c17 0 30.7-13.8 30.7-30.7c0-75.5-51.9-138.9-121.9-156.4c-8.1-2-15.9 3.3-17.9 11.3l-36 146.9L238.9 359.2l18.6-31c6.4-10.7-1.3-24.2-13.7-24.2H224 204.3c-12.4 0-20.1 13.6-13.7 24.2z"
                          />
                        </svg>
                        users
                      </Link>
                      <a
                        href="/admin/review"
                        class="flex flex-col items-center justify-center py-3 hover:text-gray-400 hover:bg-gray-700 focus:text-gray-400 focus:bg-gray-700 rounded-lg"
                      >
                        {/* <span class="sr-only">Post</span> */}
                        <svg
                          xmlns="http://www.w3.org/2000/svg"
                          viewBox="0 0 512 512"
                          width={20}
                          height={20}
                        >
                          <path
                            fill="#ffffff"
                            d="M215.4 96H144 107.8 96v8.8V144v40.4 89L.2 202.5c1.6-18.1 10.9-34.9 25.7-45.8L48 140.3V96c0-26.5 21.5-48 48-48h76.6l49.9-36.9C232.2 3.9 243.9 0 256 0s23.8 3.9 33.5 11L339.4 48H416c26.5 0 48 21.5 48 48v44.3l22.1 16.4c14.8 10.9 24.1 27.7 25.7 45.8L416 273.4v-89V144 104.8 96H404.2 368 296.6 215.4zM0 448V242.1L217.6 403.3c11.1 8.2 24.6 12.7 38.4 12.7s27.3-4.4 38.4-12.7L512 242.1V448v0c0 35.3-28.7 64-64 64H64c-35.3 0-64-28.7-64-64v0zM176 160H336c8.8 0 16 7.2 16 16s-7.2 16-16 16H176c-8.8 0-16-7.2-16-16s7.2-16 16-16zm0 64H336c8.8 0 16 7.2 16 16s-7.2 16-16 16H176c-8.8 0-16-7.2-16-16s7.2-16 16-16z"
                          />
                        </svg>
                        review
                      </a>
                    </nav>
                    <div class="inline-flex items-center justify-center h-20 w-20 border-t border-gray-700">
                      <button class="p-3   rounded-lg">
                        <Link
                          href="/"
                          class="flex flex-col items-center justify-center py-3 hover:text-gray-400  rounded-lg"
                        >
                          {/* <span class="sr-only">Post</span> */}
                          <svg
                            xmlns="http://www.w3.org/2000/svg"
                            width={15}
                            hanging={15}
                            viewBox="0 0 576 512"
                          >
                            <path
                              fill="#ffffff"
                              d="M9.4 86.6C-3.1 74.1-3.1 53.9 9.4 41.4s32.8-12.5 45.3 0l192 192c12.5 12.5 12.5 32.8 0 45.3l-192 192c-12.5 12.5-32.8 12.5-45.3 0s-12.5-32.8 0-45.3L178.7 256 9.4 86.6zM256 416H544c17.7 0 32 14.3 32 32s-14.3 32-32 32H256c-17.7 0-32-14.3-32-32s14.3-32 32-32z"
                            />
                          </svg>
                          Exit
                        </Link>
                      </button>
                    </div>
                  </div>
                </aside>
              </div>
              <div className="block w-[100%]">
                {/* -------- navbar ----- */}
                <div className="border-b-2 ">
                  <header class="flex items-center h-20 px-6 sm:px-10 bg-white ">
                    <button class="block sm:hidden relative flex-shrink-0 p-2 mr-2 text-gray-600 hover:bg-gray-100 hover:text-gray-800 focus:bg-gray-100 focus:text-gray-800 rounded-full">
                      <span class="sr-only">Menu</span>
                      <svg
                        aria-hidden="true"
                        fill="none"
                        viewBox="0 0 24 24"
                        stroke="currentColor"
                        class="h-6 w-6"
                      >
                        <path
                          stroke-linecap="round"
                          stroke-linejoin="round"
                          stroke-width="2"
                          d="M4 6h16M4 12h16M4 18h7"
                        />
                      </svg>
                    </button>
                    <div class="hidden md:flex relative w-full max-w-md sm:-ml-2">
                      <Image
                        className="shadow-lg"
                        width={190}
                        height={30}
                        src={logo}
                        alt=""
                      />
                    </div>
                    <div class="flex flex-shrink-0 items-center ml-auto">
                      <Link href={`/profile`}>
                        <button class="inline-flex items-center p-2 hover:bg-gray-100 focus:bg-gray-100 rounded-lg">
                          <span class="sr-only">User Menu</span>
                          <div class="flex flex-col md:flex md:flex-col md:items-end md:leading-tight">
                            <span class="font-semibold">
                              {userInfo?.name?.slice(0, 30)}
                            </span>
                            <span class="text-sm text-gray-600">
                              {userInfo?.ruler}
                            </span>
                          </div>
                          <span class="hidden h-12 w-12 ml-2 sm:ml-3 mr-2 md:flex justify-center items-center bg-gray-100 rounded-full overflow-hidden">
                            <FaUserTie className="text-[22px] text-[#030e10d3]" />
                          </span>
                        </button>
                      </Link>
                    </div>
                  </header>
                </div>
                {children}
              </div>
            </div>
          </>
        )}
      </body>
    </html>
  );
}
